resolver: lts-10.6
packages:
- .
extra-deps:
- cql-io-1.0.0
- cql-4.0.1
- tabl-1.0.3
- brick-0.39
- vty-5.23.1
- git: git@github.com:dabcoder/stocks.git
  commit: 068b4bbabe3f08d41c9c25bb653b6f56799de39a
